version: "3.10"

services:
  db:
    image: postgis/postgis:13-3.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autopark
    volumes:
      - ./data:/var/lib/postgresql/data/
    networks:
      - backend

  web:
    build: .
    command: bash -c "./wait-for-db.sh db && python manage.py migrate && python manage.py loaddata autopark.json && python manage.py runserver 0.0.0.0:8000 && echo 'server is up'"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:


