# Generated by Django 4.1.5 on 2023-01-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="VIN",
            field=models.CharField(default="", max_length=17, unique=True),
            preserve_default=False,
        ),
    ]
