# Generated by Django 4.1.5 on 2023-01-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto", "0002_vehicle_vin"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255, verbose_name="Бренд")),
                ("car_type", models.CharField(max_length=255, verbose_name="Тип авто")),
                (
                    "load_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Грузоподъемность",
                    ),
                ),
                (
                    "seats_number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Количество мест"
                    ),
                ),
                (
                    "fuel_tank_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Объем бака",
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Тип привода",
                    ),
                ),
                (
                    "max_speed",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Максимальная скорость"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бренд авто",
                "verbose_name_plural": "Бренды авто",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={"verbose_name": "Автомобиль", "verbose_name_plural": "Автомобили"},
        ),
    ]
