# Generated by Django 4.1.5 on 2023-01-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto", "0003_carmodel_alter_vehicle_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="fuel_tank_volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Объем бака, куб.см",
            ),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="load_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Грузоподъемность, кг",
            ),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="max_speed",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Максимальная скорость, км/ч"
            ),
        ),
    ]
