# Generated by Django 4.1.5 on 2023-01-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto", "0004_alter_carmodel_fuel_tank_volume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="brand",
            field=models.CharField(max_length=255, unique=True, verbose_name="Бренд"),
        ),
    ]
