# Generated by Django 4.1.5 on 2023-01-15 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto", "0005_alter_carmodel_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="model",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_model",
                to="auto.carmodel",
            ),
        ),
    ]
