# Generated by Django 4.1.5 on 2023-01-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auto", "0008_enterprise_alter_vehicle_model_driver_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Водитель", "verbose_name_plural": "Водители"},
        ),
        migrations.AlterModelOptions(
            name="enterprise",
            options={
                "verbose_name": "Предприятие",
                "verbose_name_plural": "Предприятия",
            },
        ),
    ]
