# Generated by Django 4.1.5 on 2023-01-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto", "0009_alter_driver_options_alter_enterprise_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="driving_experience",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Водительский стаж"
            ),
        ),
    ]
