# Generated by Django 4.1.5 on 2023-01-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto", "0010_alter_driver_driving_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="salary",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Зарплата, руб"
            ),
        ),
    ]
