# Generated by Django 4.1.5 on 2023-01-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auto", "0011_alter_driver_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="enterprise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drivers",
                to="auto.enterprise",
                verbose_name="Предприятие",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drivers",
                to="auto.vehicle",
                verbose_name="Автомобиль",
            ),
        ),
    ]
