# Generated by Django 4.1.5 on 2023-01-19 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("auto", "0012_alter_driver_enterprise_alter_driver_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enterprise",
                    models.ManyToManyField(blank=True, to="auto.enterprise"),
                ),
            ],
        ),
    ]
