# Generated by Django 4.1.5 on 2023-01-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto", "0013_manager"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manager",
            options={"verbose_name": "Менеджер", "verbose_name_plural": "Менеджеры"},
        ),
        migrations.AddField(
            model_name="manager",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AddField(
            model_name="manager",
            name="second_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="manager",
            name="enterprise",
            field=models.ManyToManyField(
                blank=True, to="auto.enterprise", verbose_name="Предприятия"
            ),
        ),
    ]
