# Generated by Django 4.1.5 on 2023-01-19 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auto", "0014_alter_manager_options_manager_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="manager",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Учетная запись",
            ),
        ),
    ]
