# Generated by Django 4.1.6 on 2023-02-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto", "0016_alter_vehicle_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="enterprise",
            field=models.ManyToManyField(
                blank=True,
                related_name="manager",
                to="auto.enterprise",
                verbose_name="Предприятия",
            ),
        ),
    ]
