# Generated by Django 4.1.7 on 2023-03-11 10:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auto", "0018_enterprise_timezone_alter_vehicle_purchase_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="timezone",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Europe/Kaliningrad", "Europe/Kaliningrad"),
                    ("Europe/Moscow", "Europe/Moscow"),
                    ("Europe/Kirov", "Europe/Kirov"),
                    ("Europe/Volgograd", "Europe/Volgograd"),
                    ("Europe/Astrakhan", "Europe/Astrakhan"),
                    ("Europe/Saratov", "Europe/Saratov"),
                    ("Europe/Ulyanovsk", "Europe/Ulyanovsk"),
                    ("Europe/Samara", "Europe/Samara"),
                    ("Asia/Yekaterinburg", "Asia/Yekaterinburg"),
                    ("Asia/Omsk", "Asia/Omsk"),
                    ("Asia/Novosibirsk", "Asia/Novosibirsk"),
                    ("Asia/Barnaul", "Asia/Barnaul"),
                    ("Asia/Tomsk", "Asia/Tomsk"),
                    ("Asia/Novokuznetsk", "Asia/Novokuznetsk"),
                    ("Asia/Krasnoyarsk", "Asia/Krasnoyarsk"),
                    ("Asia/Irkutsk", "Asia/Irkutsk"),
                    ("Asia/Chita", "Asia/Chita"),
                    ("Asia/Yakutsk", "Asia/Yakutsk"),
                    ("Asia/Khandyga", "Asia/Khandyga"),
                    ("Asia/Vladivostok", "Asia/Vladivostok"),
                    ("Asia/Ust-Nera", "Asia/Ust-Nera"),
                    ("Asia/Magadan", "Asia/Magadan"),
                    ("Asia/Sakhalin", "Asia/Sakhalin"),
                    ("Asia/Srednekolymsk", "Asia/Srednekolymsk"),
                    ("Asia/Kamchatka", "Asia/Kamchatka"),
                    ("Asia/Anadyr", "Asia/Anadyr"),
                ],
                default="UTC",
                max_length=32,
                verbose_name="Часовой пояс",
            ),
        ),
        migrations.CreateModel(
            name="GPSAutoTrack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("track", django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ("timestamp", models.DateTimeField()),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="gps_auto_track", to="auto.vehicle"
                    ),
                ),
            ],
        ),
    ]
