# Generated by Django 4.1.7 on 2023-03-12 17:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0021_remove_gpsautotrack_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='GPS положение')),
                ('timestamp', models.DateTimeField(null=True, verbose_name='Время записи')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_data', to='auto.vehicle', verbose_name='Авто')),
            ],
            options={
                'verbose_name': 'GPS данные',
                'verbose_name_plural': 'GPS данные',
            },
        ),
    ]
