# Generated by Django 4.1.7 on 2023-03-16 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0022_gpsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Время начала поездки')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания поездки')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_rides', to='auto.vehicle', verbose_name='Авто')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
    ]
