# Generated by Django 4.1.7 on 2023-03-19 19:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0023_autoride'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoride',
            name='end_point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Точка окончания поездки'),
        ),
        migrations.AddField(
            model_name='autoride',
            name='start_point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Точка начала поездки'),
        ),
    ]
