# Generated by Django 4.2 on 2023-04-07 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetterBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, unique=True, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='BetterDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата, руб')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='BetterEnterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предприятия')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('timezone', models.CharField(choices=[('Europe/Kaliningrad', 'Europe/Kaliningrad'), ('Europe/Moscow', 'Europe/Moscow'), ('Europe/Kirov', 'Europe/Kirov'), ('Europe/Volgograd', 'Europe/Volgograd'), ('Europe/Astrakhan', 'Europe/Astrakhan'), ('Europe/Saratov', 'Europe/Saratov'), ('Europe/Ulyanovsk', 'Europe/Ulyanovsk'), ('Europe/Samara', 'Europe/Samara'), ('Asia/Yekaterinburg', 'Asia/Yekaterinburg'), ('Asia/Omsk', 'Asia/Omsk'), ('Asia/Novosibirsk', 'Asia/Novosibirsk'), ('Asia/Barnaul', 'Asia/Barnaul'), ('Asia/Tomsk', 'Asia/Tomsk'), ('Asia/Novokuznetsk', 'Asia/Novokuznetsk'), ('Asia/Krasnoyarsk', 'Asia/Krasnoyarsk'), ('Asia/Irkutsk', 'Asia/Irkutsk'), ('Asia/Chita', 'Asia/Chita'), ('Asia/Yakutsk', 'Asia/Yakutsk'), ('Asia/Khandyga', 'Asia/Khandyga'), ('Asia/Vladivostok', 'Asia/Vladivostok'), ('Asia/Ust-Nera', 'Asia/Ust-Nera'), ('Asia/Magadan', 'Asia/Magadan'), ('Asia/Sakhalin', 'Asia/Sakhalin'), ('Asia/Srednekolymsk', 'Asia/Srednekolymsk'), ('Asia/Kamchatka', 'Asia/Kamchatka'), ('Asia/Anadyr', 'Asia/Anadyr')], default='UTC', max_length=32, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
        migrations.CreateModel(
            name='BetterVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=255, verbose_name='Номер регистрации')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='better_auto.betterbrand', verbose_name='Бренд')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='better_auto.betterdriver', verbose_name='Водитель')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='better_auto.betterenterprise', verbose_name='Предприятие')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.AddField(
            model_name='betterdriver',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='better_auto.betterenterprise', verbose_name='Предприятие'),
        ),
        migrations.AddField(
            model_name='betterdriver',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='better_auto.bettervehicle', verbose_name='Автомобиль'),
        ),
    ]
